### ISSUE TITLE
Use Cake Contrib icon

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Prca.Issues.InspectCode#30]
Use Cake Contrib icon instead of official Cake icon

**Comment by gep13** [comment]
@pascalberger I would suggest using the rawgit link to the icon, similar to what we do in the Chocolatey Core Team Repo.

**Comment by pascalberger** [comment]
@gep13 And also fix it to a specific commit? Or use latest with the advantages that changes appear automatically but if something is moved it breaks everything

**Comment by gep13** [comment]
Yeah, I would fix it to a specific commit, similar to what we do over there.  That way it will always work, regardless of movements.  The logo is unlikely to change now that we have it, but that doesn't mean that repo won't be altered.

**Comment by gep13** [comment]
@pascalberger https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png

Thoughts?

**Comment by pascalberger** [comment]
@gep13 Looks good
